CREATE TABLE `usuarios`(
`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`nome` VARCHAR(50) NOT NULL,
`email` VARCHAR(50) NOT NULL UNIQUE,
`senha` VARCHAR(60) NOT NULL,
`perfil` VARCHAR(60) NOT NULL
);